### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by iazdan** [Kroery/DiffMOT#7]
Hi, 
Thanks for your wonderful work. Would that be possible to add a demo.py script for testing videos? 

Thanks

**Comment by SkalskiP** [comment]
Hi 👋🏻 Google Colab showing how to set up and run the tracker would be awesome as well.

**Comment by SangbumChoi** [comment]
@iazdan @SkalskiP https://github.com/Kroery/DiffMOT/pull/11#issue-2287067204
Enjoy and tell me if there is something wrong

**Comment by GuHuangAI** [comment]
@SangbumChoi 
Excellent work!

**Comment by SkalskiP** [comment]
@SangbumChoi The one problem I see is that, currently, DiffMOT is tightly entangled with YOLOX. In theory, it could work with any detector, but there is not easy way to do it currently.

**Comment by panwpalo** [comment]
Thank yoy @SangbumChoi  for your quick response. I get the error below while executing the demo.py file. Could you also fix this issue ? 

  File "demo.py", line 10, in <module>
    from diffmot import DiffMOT
  File "DiffMOT/diffmot.py", line 13, in <module>
    from models.autoencoder import D2MP
ModuleNotFoundError: No module named 'models.autoencoder'

**Comment by SangbumChoi** [comment]
@panwpalo that is the installation error not the code part. please follow the basic installation part.

**Comment by SangbumChoi** [comment]
@SkalskiP That is true, you do not need to have YOLOX extension. You only need is detection result prepared as follow
`<frame>, <x>, <y>, <x2>, <y2>, <confidence> `
with the txt file in the dataset_dir.

Do you have the mp4 and the result txt file?

**Comment by SangbumChoi** [comment]
@GuHuangAI FYI, I only tested in DanceTrack and I think we need some further modification for other weight file too

**Comment by SkalskiP** [comment]
@SangbumChoi yes, I have both files. What should I do now?

**Comment by SangbumChoi** [comment]
@SkalskiP Could you share here? I can modify the code to make it compatible

**Comment by MuhammadRamzan4** [comment]
@SangbumChoi  Try to use your demo.py file but facing this error
![image](https://github.com/Kroery/DiffMOT/assets/115547990/0f1c9ec3-eec7-469c-a60b-e286ec61433b)

**Comment by panwpalo** [comment]
> @panwpalo that is the installation error not the code part. please follow the basic installation part.

I followed the installation instructions step by step and everything was installed successfully. The only thing that I changed was faiss-gpu- -> faiss-cpu since I am running the dempy.py on Macos. However I am still getting the same error.

**Comment by SangbumChoi** [comment]
@MuhammadRamzan4 I think you do not have image files path.

**Comment by panwpalo** [comment]
After running the demo.py the only output that I see is the video being converted into images and it gets stuck afterward! Any clue ?


2024-05-10 16:09:20 [DEBUG]: matplotlib data path: /opt/anaconda3/envs/diffmot/lib/python3.9/site-packages/matplotlib/mpl-data
2024-05-10 16:09:20 [DEBUG]: CONFIGDIR=/.matplotlib
2024-05-10 16:09:20 [DEBUG]: interactive is False
2024-05-10 16:09:20 [DEBUG]: platform is darwin
2024-05-10 16:09:20 [DEBUG]: CACHEDIR=.matplotlib
2024-05-10 16:09:20 [DEBUG]: Using fontManager instance from.matplotlib/fontlist-v330.json
> Train Dataset built!
File 'external/weights/dance_sbs_S50.pth' already exists. Skipping download.
File 'experiments/mot_ddm_1000_deeper/DanceTrack_epoch800.pt' already exists. Skipping download.
File 'weights/DanceTrack_yolox_s.tar' already exists. Skipping download.

**Comment by SangbumChoi** [comment]
@panwpalo You should wait until the YOLO process, how long is your video size? usually 300 frames gets done in a 10 seonds in good GPU

**Comment by cedricnam** [comment]
@SangbumChoi i got error
![Screenshot from 2024-05-14 10-44-53](https://github.com/Kroery/DiffMOT/assets/101238328/f6a37f3f-75b4-47b1-89cf-b55822c37d16)

**Comment by panwpalo** [comment]
I used the default video and yolox and I am running it on cpu. Is the mmtracking implementation faster than this Repo?

**Comment by SangbumChoi** [comment]
@panwpalo I think it is due to using cpu use light yolo model

**Comment by Coronal-Halo** [comment]
<img width="547" alt="bug" src="https://github.com/user-attachments/assets/fc01b5b7-f15b-4a41-95e9-49c611c12975">

In the "compute_embedding(self, img, bbox, tag)" function, when you clip the resulting bounding boxes, the 'results' may end up being empty, as shown in the above image (both p[0] and p[2] are 0 due to clipping -- they were originally negative). In this case, the empty 'results' variable will cause errors in the following code (for example, in the next line 135: crop = cv2.cvtColor(crop, cv2.COLOR_BGR2RGB), since cv2.cvtColor does not accept empty array). How do you resolve this bug ?

**Comment by Abhipray04** [comment]
@SangbumChoi Thanks for doing this! It helped a lot. 

A quick question - how can I make it work for SportsMOT instead of DanceTrack? What modifications do I need to make to use SportsMOT weights?

Thanks again.

**Comment by Rainbow5495** [comment]
> @SangbumChoi Try to use your demo.py file but facing this error ![image](https://private-user-images.githubusercontent.com/115547990/329693182-0f1c9ec3-eec7-469c-a60b-e286ec61433b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDk5OTEsIm5iZiI6MTcyOTg0OTY5MSwicGF0aCI6Ii8xMTU1NDc5OTAvMzI5NjkzMTgyLTBmMWM5ZWMzLWVlYzctNDY5Yy1hNjBiLWUyODZlYzYxNDMzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwOTQ4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGJiMDUxOGE4MGU5MzRjNzVlNjA3Zjk1OGZjY2E4MDEzOTUyNTI3ZDFmZGU1MzYyNjVkNGM4MmY2ZDJlNmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1s07e-Zd2cSBWzXvGDtRTwhAxrIlQz62GLrQVp4vpzQ)

I have the same problem. Have you solved it?

**Comment by Rainbow5495** [comment]
> @panwpalo I think it is due to using cpu use light yolo model

Could you please offer me some help? Thanks a lot!

**Comment by weiwencengyu** [comment]
> [@iazdan](https://github.com/iazdan) [@SkalskiP](https://github.com/SkalskiP) [#11 (comment)](https://github.com/Kroery/DiffMOT/pull/11#issue-2287067204) Enjoy and tell me if there is something wrong


I have this problem,could you please help me?

Error running Python script:
usage: YOLOX Demo! [-h] [-expn EXPERIMENT_NAME] [-n NAME] [--path PATH]
                   [--camid CAMID] [--save_result] [-f EXP_FILE] [-c CKPT]
                   [--device DEVICE] [--conf CONF] [--nms NMS] [--tsize TSIZE]
                   [--fp16] [--legacy] [--fuse] [--trt]
                   demo
YOLOX Demo!: error: unrecognized arguments: --output_txt_path outputs --num_classes 1 --save_txt

2025-02-18 18:42:51 [INFO]: Config:
2025-02-18 18:42:51 [INFO]: {'eps': 0.001, 'eval_mode': True, 'lr': 0.0001, 'data_dir': './outputs', 'diffnet': 'HMINet', 'interval': 5, 'augment': True, 'encoder_dim': 256, 'tf_layer': 3, 'epochs': 800, 'batch_size': 2048, 'seed': 123, 'eval_every': 20, 'gpus': [0, 1, 2, 3], 'eval_at': 800, 'det_dir': './outputs/detections/', 'info_dir': './outputs', 'reid_dir': 'weights/embedding', 'save_dir': 'outputs/yolox_m_lt_ddm_1000eps_deeper_800_1rev', 'eval_expname': 'mot_ddm_1000_deeper', 'high_thres': 0.4, 'low_thres': 0.1, 'w_assoc_emb': 2.2, 'aw_param': 1.7, 'preprocess_workers': 16, 'device': 'cuda', 'eval_device': 'None', 'video_path': 'mot2004.mp4', 'output_video_path': 'outputs/weapon/img6', 'output_txt_path': 'outputs', 'weight': 'MOT20_yolox_x.tar', 'yolox_type': 'yolox-x', 'config': './configs/demo_test.yaml', 'dataset': 'MOT20', 'exp_name': 'demo_test'}
2025-02-18 18:42:51 [INFO]: 

2025-02-18 18:42:51 [INFO]: Eval on:
2025-02-18 18:42:51 [INFO]: MOT20
2025-02-18 18:42:51 [INFO]: 

> Directory built!
> Model built!
Tracker path: ./outputs/weapon/img1/*.txt
Trackers: []
Sequence: weapon
CDS: []
NDS: []
Traceback (most recent call last):
  File "/root/autodl-tmp/DiffMOT-main/demo.py", line 178, in <module>
    main(args=args)
  File "/root/autodl-tmp/DiffMOT-main/demo.py", line 106, in main
    agent = DiffMOT(config)
  File "/root/autodl-tmp/DiffMOT-main/diffmot.py", line 51, in __init__
    self._build()
  File "/root/autodl-tmp/DiffMOT-main/diffmot.py", line 140, in _build
    self._build_train_loader()
  File "/root/autodl-tmp/DiffMOT-main/diffmot.py", line 203, in _build_train_loader
    self.train_dataset = DiffMOTDataset(data_path, config)
  File "/root/autodl-tmp/DiffMOT-main/dataset/dataset.py", line 57, in __init__
    lastindex = self.cds[seq][-1] + self.nds[seq][-1]
IndexError: list index out of range

**Comment by weiwencengyu** [comment]
@SangbumChoi I have this prolem,could you please help me?
Error running Python script:
usage: YOLOX Demo! [-h] [-expn EXPERIMENT_NAME] [-n NAME] [--path PATH]
                   [--camid CAMID] [--save_result] [-f EXP_FILE] [-c CKPT]
                   [--device DEVICE] [--conf CONF] [--nms NMS] [--tsize TSIZE]
                   [--fp16] [--legacy] [--fuse] [--trt]
                   demo
YOLOX Demo!: error: unrecognized arguments: --output_txt_path outputs --num_classes 1 --save_txt

2025-02-18 18:42:51 [INFO]: Config:
2025-02-18 18:42:51 [INFO]: {'eps': 0.001, 'eval_mode': True, 'lr': 0.0001, 'data_dir': './outputs', 'diffnet': 'HMINet', 'interval': 5, 'augment': True, 'encoder_dim': 256, 'tf_layer': 3, 'epochs': 800, 'batch_size': 2048, 'seed': 123, 'eval_every': 20, 'gpus': [0, 1, 2, 3], 'eval_at': 800, 'det_dir': './outputs/detections/', 'info_dir': './outputs', 'reid_dir': 'weights/embedding', 'save_dir': 'outputs/yolox_m_lt_ddm_1000eps_deeper_800_1rev', 'eval_expname': 'mot_ddm_1000_deeper', 'high_thres': 0.4, 'low_thres': 0.1, 'w_assoc_emb': 2.2, 'aw_param': 1.7, 'preprocess_workers': 16, 'device': 'cuda', 'eval_device': 'None', 'video_path': 'mot2004.mp4', 'output_video_path': 'outputs/weapon/img6', 'output_txt_path': 'outputs', 'weight': 'MOT20_yolox_x.tar', 'yolox_type': 'yolox-x', 'config': './configs/demo_test.yaml', 'dataset': 'MOT20', 'exp_name': 'demo_test'}
2025-02-18 18:42:51 [INFO]: 

2025-02-18 18:42:51 [INFO]: Eval on:
2025-02-18 18:42:51 [INFO]: MOT20
2025-02-18 18:42:51 [INFO]: 

> Directory built!
> Model built!
Tracker path: ./outputs/weapon/img1/*.txt
Trackers: []
Sequence: weapon
CDS: []
NDS: []
Traceback (most recent call last):
  File "/root/autodl-tmp/DiffMOT-main/demo.py", line 178, in <module>
    main(args=args)
  File "/root/autodl-tmp/DiffMOT-main/demo.py", line 106, in main
    agent = DiffMOT(config)
  File "/root/autodl-tmp/DiffMOT-main/diffmot.py", line 51, in __init__
    self._build()
  File "/root/autodl-tmp/DiffMOT-main/diffmot.py", line 140, in _build
    self._build_train_loader()
  File "/root/autodl-tmp/DiffMOT-main/diffmot.py", line 203, in _build_train_loader
    self.train_dataset = DiffMOTDataset(data_path, config)
  File "/root/autodl-tmp/DiffMOT-main/dataset/dataset.py", line 57, in __init__
    lastindex = self.cds[seq][-1] + self.nds[seq][-1]
IndexError: list index out of range
